# 
# To create the conda environment:
# $ conda env create -f base.yaml
# 
# To update the conda environment:
# $ conda env update -f base.yaml
# 
# To register the conda environment in Jupyter:
# $ conda activate base
# $ python -m ipykernel install --user --name base --display-name "Python (base)"
# 
name: base
channels:
- defaults
- conda-forge
- pytorch
- fastai
dependencies:
- bottleneck==1.2.1
- cornac>=1.1.2
- cudatoolkit=10.0
- dask>=0.17.1
- fastai==1.0.46
- fastparquet>=0.1.6
- ipykernel>=4.6.1
- jupyter>=1.0.0
- jupyterlab>=2.2.7
- lightfm>=1.15
- lightgbm==2.2.1
- matplotlib>=2.2.2
- mock==2.0.0
- nltk>=3.4
- nodejs>=14.10.1
- numba>=0.38.1
- numpy>=1.13.3
- pandas>=0.23.4,<1.0.0
- papermill==0.19.1
- pip>=19.2
- plotly>=4.10.0
- pyarrow>=0.8.0
- pytest>=3.6.4
- python-language-server>=0.26.1
- python==3.6.10
- pytorch>=1.0.0
- scikit-learn>=0.19.1
- scikit-surprise>=1.0.6
- scipy>=1.0.0
- seaborn>=0.8.1
- swig==3.0.12
- tqdm>=4.31.1
- xgboost>=1.2.0
- pip:
  - azure-cli-core>=2.0.75
  - azure-mgmt-cosmosdb>=0.8.0
  - azure-storage-blob<=2.1.0
  - azureml-sdk[notebooks,tensorboard]==1.0.69
  - black>=18.6b4
  - category_encoders>=1.3.0
  - databricks-cli==0.8.6
  - dataclasses>=0.6
  - hyperopt==0.1.1
  - idna==2.7
  - jupyterlab_code_formatter
  - locustio==0.11.0
  - memory-profiler>=0.54.0
  - nbconvert==5.5.0
  - nni==1.5
  - nvidia-ml-py3>=7.352.0
  - pydocumentdb>=2.3.3
  - pymanopt==0.2.5
  - pyspark==3.0.1
  - tensorboard
  - tensorflow-gpu==1.15.2
  - transformers==2.5.0
  # - xlearn==0.40a1
